### ISSUE TITLE
how to update the vocab

### ISSUE THREAD

**Issue by vgoklani** [dsindex/textsum#1]
Thanks for putting together this example!

How are you updating the vocab?

**Comment by dsindex** [comment]
i did't even consider the vocab file. 
if i find the way, i will notice to you.

**Comment by dsindex** [comment]
@vgoklani 

i found the bellow comment in [README.md](https://github.com/tensorflow/models/tree/master/textsum)

```
vocabulary size: Most frequent 200k words from dataset's article and summaries.
```

so, i guess how to build the vocab file.

- prepare your own training data
- preprocessing
  - append '\<d\>', '\<s\>', '\</s\>', '\</d\>' to articles and summaries
  - replace all digits to '#'
- build vocab file
  - similar way to http://www.wildml.com/2015/09/recurrent-neural-networks-tutorial-part-2-implementing-a-language-model-rnn-with-python-numpy-and-theano/
  - tokenize articles and summaries(by nltk(?))
  - build word_freq, id_to_word, word_to_id dictionary
  - cut word items bellow freq=200K => vocab[1]
  - add '\<UNK\>' whose frequency is the sum of all word's not in vocab[1]
  - add '\<PAD\>' with some lower frequency(ex,   5) (not sure) 
- convert text to binary format using `data_convert_example.py` for input
  - you need to prepare formatted text file
  ```
  ex)
  abstract=hello world \t  summary=article=hello world......
  ```
